### Data Pre-processing

In [254]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [255]:
df_fake = pd.read_csv(r'F:\ML\Project\archive\Fake.csv') # Load 'fake news' dataset

In [256]:
df_fake.head(10)

title  \
0                          Donald Trump Sends Out Embarrassing New Year’s Eve Message; This is Disturbing   
1                                    Drunk Bragging Trump Staffer Started Russian Collusion Investigation   
2               Sheriff David Clarke Becomes An Internet Joke For Threatening To Poke People ‘In The Eye’   
3                           Trump Is So Obsessed He Even Has Obama’s Name Coded Into His Website (IMAGES)   
4                                   Pope Francis Just Called Out Donald Trump During His Christmas Speech   
5                       Racist Alabama Cops Brutalize Black Boy While He Is In Handcuffs (GRAPHIC IMAGES)   
6                      Fresh Off The Golf Course, Trump Lashes Out At FBI Deputy Director And James Comey   
7                  Trump Said Some INSANELY Racist Stuff Inside The Oval Office, And Witnesses Back It Up   
8   Former CIA Director Slams Trump Over UN Bullying, Openly Suggests He’s Acting Like A Dictator (TWEET)   
9                        WATCH: Brand-New Pro-Trump Ad Features So Much A** Kissing It Will Make You Sick   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

In [257]:
df_fake = df_fake.drop(['date', 'subject'], axis=1) # Drop unwanted columns

In [258]:
df_fake['target'] = 0 # Class value for fake news is set to 0

In [259]:
df_fake.head(10)

title  \
0                          Donald Trump Sends Out Embarrassing New Year’s Eve Message; This is Disturbing   
1                                    Drunk Bragging Trump Staffer Started Russian Collusion Investigation   
2               Sheriff David Clarke Becomes An Internet Joke For Threatening To Poke People ‘In The Eye’   
3                           Trump Is So Obsessed He Even Has Obama’s Name Coded Into His Website (IMAGES)   
4                                   Pope Francis Just Called Out Donald Trump During His Christmas Speech   
5                       Racist Alabama Cops Brutalize Black Boy While He Is In Handcuffs (GRAPHIC IMAGES)   
6                      Fresh Off The Golf Course, Trump Lashes Out At FBI Deputy Director And James Comey   
7                  Trump Said Some INSANELY Racist Stuff Inside The Oval Office, And Witnesses Back It Up   
8   Former CIA Director Slams Trump Over UN Bullying, Openly Suggests He’s Acting Like A Dictator (TWEET)   
9                        WATCH: Brand-New Pro-Trump Ad Features So Much A** Kissing It Will Make You Sick   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

In [260]:
df_true = pd.read_csv(r'F:\ML\Project\archive\True.csv') # Load 'true news' dataset

In [261]:
df_true.head(10)

title  \
0              As U.S. budget fight looms, Republicans flip their fiscal script   
1              U.S. military to accept transgender recruits on Monday: Pentagon   
2                  Senior U.S. Republican senator: 'Let Mr. Mueller do his job'   
3                   FBI Russia probe helped by Australian diplomat tip-off: NYT   
4         Trump wants Postal Service to charge 'much more' for Amazon shipments   
5              White House, Congress prepare for talks on spending, immigration   
6               Trump says Russia probe will be fair, but timeline unclear: NYT   
7                  Factbox: Trump on Twitter (Dec 29) - Approval rating, Amazon   
8                                    Trump on Twitter (Dec 28) - Global Warming   
9  Alabama official to certify Senator-elect Jones today despite challenge: CNN   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

In [262]:
df_true = df_true.drop(['date', 'subject'], axis=1) # Drop unwanted columns

In [263]:
df_true['target'] = 1 # Set the class value for true news as 1

In [264]:
df_true.head(10)

title  \
0              As U.S. budget fight looms, Republicans flip their fiscal script   
1              U.S. military to accept transgender recruits on Monday: Pentagon   
2                  Senior U.S. Republican senator: 'Let Mr. Mueller do his job'   
3                   FBI Russia probe helped by Australian diplomat tip-off: NYT   
4         Trump wants Postal Service to charge 'much more' for Amazon shipments   
5              White House, Congress prepare for talks on spending, immigration   
6               Trump says Russia probe will be fair, but timeline unclear: NYT   
7                  Factbox: Trump on Twitter (Dec 29) - Approval rating, Amazon   
8                                    Trump on Twitter (Dec 28) - Global Warming   
9  Alabama official to certify Senator-elect Jones today despite challenge: CNN   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

In [267]:
df = pd.concat([df_fake, df_true]) # Combine/Concatenate both the dataframes

In [297]:
df.head(10)
#df['target']

title  \
0                            Donald Trump Sends Out Embarrassing New Year’s Eve Message; This Disturbing   
1                                   Drunk Bragging Trump Staffer Started Russian Collusion Investigation   
2              Sheriff David Clarke Becomes An Internet Joke For Threatening To Poke People ‘In The Eye’   
3                          Trump Is So Obsessed He Even Has Obama’s Name Coded Into His Website (IMAGES)   
4                                  Pope Francis Just Called Out Donald Trump During His Christmas Speech   
5                      Racist Alabama Cops Brutalize Black Boy While He Is In Handcuffs (GRAPHIC IMAGES)   
6                     Fresh Off The Golf Course, Trump Lashes Out At FBI Deputy Director And James Comey   
7                 Trump Said Some INSANELY Racist Stuff Inside The Oval Office, And Witnesses Back It Up   
8  Former CIA Director Slams Trump Over UN Bullying, Openly Suggests He’s Acting Like A Dictator (TWEET)   
9                       WATCH: Brand-New Pro-Trump Ad Features So Much A** Kissing It Will Make You Sick   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             text  \
0                                                                                                                                        

In [269]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 44898 entries, 0 to 21416
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   title   44898 non-null  object
 1   text    44898 non-null  object
 2   target  44898 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 1.4+ MB


In [270]:
df['title'].isnull().values.any() # Check for NULL values in 'title' column

False

In [271]:
df['text'].isnull().values.any() # Check for NULL values in 'text' column

False

In [272]:
df['target'].isnull().values.any() # Check for NULL values in 'target' column

False

In [273]:
# Reference - https://www.datasnips.com/58/remove-stop-words-from-text-in-dataframe-column/

# Remove stop words
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
df['title'] = df['title'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))
df['text'] = df['text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))
df.head(10)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


title  \
0                            Donald Trump Sends Out Embarrassing New Year’s Eve Message; This Disturbing   
1                                   Drunk Bragging Trump Staffer Started Russian Collusion Investigation   
2              Sheriff David Clarke Becomes An Internet Joke For Threatening To Poke People ‘In The Eye’   
3                          Trump Is So Obsessed He Even Has Obama’s Name Coded Into His Website (IMAGES)   
4                                  Pope Francis Just Called Out Donald Trump During His Christmas Speech   
5                      Racist Alabama Cops Brutalize Black Boy While He Is In Handcuffs (GRAPHIC IMAGES)   
6                     Fresh Off The Golf Course, Trump Lashes Out At FBI Deputy Director And James Comey   
7                 Trump Said Some INSANELY Racist Stuff Inside The Oval Office, And Witnesses Back It Up   
8  Former CIA Director Slams Trump Over UN Bullying, Openly Suggests He’s Acting Like A Dictator (TWEET)   
9                       WATCH: Brand-New Pro-Trump Ad Features So Much A** Kissing It Will Make You Sick   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             text  \
0                                                                                                                                        

### Set up the features and target

In [274]:
# Get X-axis (set(s) of features)

#x = df[['title', 'text']]
x = df[['text']]
x.head()

text
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Donald Trump wish Americans Happy New Year leave that. Instead, give shout enemies, haters dishonest fake news media. The former reality show star one job it. As Country rapidly grows stronger smarter, I want wish friends, supporters, enemies, haters, even dishonest Fake News Media, Happy Healthy New Year, President Angry Pants tweeted. 2018 great year America! As Country rapidly grows stronger smarter, I want wish friends, supporters, enemies, haters, even dishonest Fake News Media, Happy Healthy New Year. 2018 great year America! Donald J. Trump (@realDonaldTrump) December 31, 2017Trump tweet went welll expect.What kind president sends New Year greeting like despicable, petty, infantile gibberish? Only Trump! His lack decency even allow rise gutter long enough wish American citizens happy new year! Bishop Talbert Swan (@TalbertSwan) December 31, 2017no one likes Calvin (@calvinstowell) December 31, 2017Your impeachment would make 2018 great year America, I also accept regaining control Congress. Miranda Yaver (@mirandayaver) December 31, 2017Do hear talk? When include many people hate wonder? Why hate me? Alan Sandoval (@AlanSandoval13) December 31, 2017Who uses word Haters New Years wish?? Marlene (@marlene399) December 31, 2017You say happy new year? Koren pollitt (@Korencarpenter) December 31, 2017Here Trump New Year Eve tweet 2016.Happy New Year all, including many enemies fought lost badly know do. Love! Donald J. Trump (@realDonaldTrump) December 31, 2016This nothing new Trump. He years.Trump directed messages enemies haters New Year s, Easter, Thanksgiving, anniversary 9/11. pic.twitter.com/4FPAe2KypA Daniel Dale (@ddale8) December 31, 2017Trump holiday tweets clearly presidential.How long work Hallmark becoming President? Steven Goodine (@SGoodine) December 31, 2017He always like . . . difference last years, filter breaking down. Roy Schulze (@thbthttt) December 31, 2017Who, apart teenager uses term haters? Wendy (@WendyWhistles) December 31, 2017he fucking 5 year old Who Knows (@rainyday80) December 31, 2017So, people voted hole thinking would change got power, wrong! 70-year-old men change year older.Photo Andrew Burton/Getty Images.
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

In [275]:
max(x['text'])

'youngers days becoming moist pic.twitter.com/ctKxUQXIAz 6Paths OfA WolfsPain (@GiovanniiDC) September 21, 2016THUGS BEATING UP A RANDOM WHITE GUY:Why attacking random guy?#CharlotteProtest #Charlotte pic.twitter.com/Wt6q7o5iwc Andrew Quackson (@AndrewQuackson) September 22, 2016 RIOTERS TRYING TO LIGHT A GUY ON FIRE: Peaceful Protesters trying keep man warm attempting light fire#CharlotteProtest #Charlotte pic.twitter.com/hWeVAadoi4 Andrew Quackson (@AndrewQuackson) September 22, 2016 RIOTERS BREAKING INTO A STORE:Protestors rush souvenir store #Charlotte #CharlotteRiots pic.twitter.com/r0KmeyTkTs myrcat (@Myrna_Perez) September 22, 2016 RIOTERS PULLING PEOPLE FROM CARS:Agitators attempting surround pull people vehicles. #CharlotteRiot/#CharlotteProtest pic.twitter.com/V5ZokkRxlX Audit The Media ?? (@AuditTheMedia) September 22, 2016 STEALING JUST BECAUSE Protesters getting even ATM responsible death black man.#Charlotte #CharlotteProtest pic.twitter.com/2wDpOgys8E Andrew Quackson (@A

In [276]:
# Get Y-axis (Class label)

y = df['target']
y

0        0
1        0
2        0
3        0
4        0
        ..
21412    1
21413    1
21414    1
21415    1
21416    1
Name: target, Length: 44898, dtype: int64

### Feature Extraction - Count Vectorization

In [277]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [278]:
# Split data
x_train, x_test, y_train, y_test = train_test_split(df['text'], df['target'], test_size=0.2, random_state=0)

In [279]:
x_train

14907                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

In [280]:
tfidf = TfidfVectorizer()
x_train_tfidf = tfidf.fit_transform(x_train) # Convert training data to vectors
x_test_tfidf = tfidf.transform(x_test) # Convert testing data to vectors

### Decision Tree 

In [193]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

In [51]:
tmp = [] # A list to maintain the mean of cross-value scores
cvs = [] # A list to maintain the cross-value scores

for i in range(1, 11): # Loop to find the best 'max_depth (levels in a DT)' value
    clf = DecisionTreeClassifier(max_depth = i, criterion = "entropy").fit(x_train_tfidf, y_train) # Compute DT
    cvs = cross_val_score(clf, x_train_tfidf, y_train, cv = 5) # Find cross-value score for max_depth=i
    tmp.append(cvs.mean())

In [52]:
# Find the maximum mean cross-vaue score
for i in range(len(tmp)):
    if tmp[i] == np.max(tmp):
        print(i+1, ' : ', tmp[i])

9  :  0.9958238402848597


In [194]:
# As 9 is the max_depth value for which the cross-value score was maximum, using that compute DT
DT_clf = DecisionTreeClassifier(max_depth = 9, criterion = "entropy").fit(x_train_tfidf, y_train)

In [195]:
y_pred = DT_clf.predict(x_test_tfidf) # Prediction on test data using the DT model
y_pred

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [196]:
# Find accuracy score
from sklearn.metrics import accuracy_score
accuracy_score_DT = accuracy_score(y_test, y_pred)
accuracy_score_DT

0.994543429844098

In [197]:
# Compute confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[4612,   23],
       [  26, 4319]], dtype=int64)

In [198]:
# Print the classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      4635
           1       0.99      0.99      0.99      4345

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980



### Random Forest

In [199]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [27]:
tmp = [] # A list to maintain the mean of cross-value scores
cvs = [] # A list to maintain the cross-value scores

for i in range(100, 501, 100): # Loop to find the best number of decision trees (n_estimators) to combine
    clf = RandomForestClassifier(max_depth=10, criterion='entropy', n_estimators=i, random_state=2).fit(x_train_tfidf, y_train) # Compute RF
    cvs = cross_val_score(clf, x_train_tfidf, y_train, cv = 5) # Find cross-value score for n_estimators=i
    tmp.append(cvs.mean())

In [28]:
# Find the maximum mean cross-vaue score
for i in range(len(tmp)):
    if tmp[i] == np.max(tmp):
        print(i+1, ' : ', tmp[i])

3  :  0.9780889098145925


In [200]:
# Mean cross-value score is maximum when n_estimators=300, so use that to fit the model
RF_clf = RandomForestClassifier(max_depth=10, criterion='entropy', n_estimators=300, random_state=2).fit(x_train_tfidf, y_train)

In [201]:
y_pred = RF_clf.predict(x_test_tfidf) # Prediction on test data using the RF model
y_pred

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [202]:
# Find accuracy score
from sklearn.metrics import accuracy_score
accuracy_score_RF = accuracy_score(y_test, y_pred)
accuracy_score_RF

0.9806236080178173

In [203]:
# Compute confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[4581,   54],
       [ 120, 4225]], dtype=int64)

In [204]:
# Print classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98      4635
           1       0.99      0.97      0.98      4345

    accuracy                           0.98      8980
   macro avg       0.98      0.98      0.98      8980
weighted avg       0.98      0.98      0.98      8980



### Logistic Regression

In [205]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [206]:
# Fit LR model using 'l2' regularization
LR_clf = LogisticRegression(solver='lbfgs', penalty='l2', random_state=2).fit(x_train_tfidf, y_train)

In [207]:
y_pred = LR_clf.predict(x_test_tfidf) # Prediction on test data using the LR model
y_pred

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [208]:
# Find accuracy score
from sklearn.metrics import accuracy_score
accuracy_score_LR = accuracy_score(y_test, y_pred)
accuracy_score_LR

0.9876391982182628

In [209]:
# Compute confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[4580,   55],
       [  56, 4289]], dtype=int64)

In [210]:
# Print classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4635
           1       0.99      0.99      0.99      4345

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980



### KNN

In [211]:
from sklearn.neighbors import KNeighborsClassifier

In [212]:
neigh = KNeighborsClassifier(n_neighbors=4).fit(x_train_tfidf, y_train) # Fit KNN model using K=4

In [213]:
y_pred = neigh.predict(x_test_tfidf) # Prediction on test data using the KNN model
y_pred

C:\Users\HP\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [214]:
# Find accuracy score
from sklearn.metrics import accuracy_score
accuracy_score_KNN = accuracy_score(y_test, y_pred)
accuracy_score_KNN

0.6347438752783965

In [215]:
# Compute confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[4602,   33],
       [3247, 1098]], dtype=int64)

In [216]:
# Print classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.59      0.99      0.74      4635
           1       0.97      0.25      0.40      4345

    accuracy                           0.63      8980
   macro avg       0.78      0.62      0.57      8980
weighted avg       0.77      0.63      0.57      8980



### Naive Bayes 

In [217]:
#from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

In [218]:
#clf = GaussianNB().fit(x_train_tfidf.todense(), y_train)
NB_clf = MultinomialNB().fit(x_train_tfidf, y_train) # Fit MultinomialNB

In [219]:
y_pred = NB_clf.predict(x_test_tfidf) # Prediction on test data using NB model
y_pred

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [220]:
# Find accuracy score
from sklearn.metrics import accuracy_score
accuracy_score_NB = accuracy_score(y_test, y_pred)
accuracy_score_NB

0.9391982182628063

In [221]:
# Compute confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[4402,  233],
       [ 313, 4032]], dtype=int64)

In [222]:
# Print classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94      4635
           1       0.95      0.93      0.94      4345

    accuracy                           0.94      8980
   macro avg       0.94      0.94      0.94      8980
weighted avg       0.94      0.94      0.94      8980



### Neural Networks

In [88]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score

In [89]:
tmp = [] # Empty list which will be needed to store mean of cross-val scores
for i in range(1, 6): # Outer-loop runs for the number of hidden layers
    for j in range(1, 6): # Inner-loop runs for the number of hidden units in each layer
        clf = MLPClassifier(hidden_layer_sizes=(j,i), random_state=2, max_iter=500, alpha=0.01) # NNet CLassifier
        scores = cross_val_score(clf, x_train_tfidf, y_train, cv=5) # 5-fold Cross Validation
        print('Cross Validation Score for ', i, ' layer(s) and ', j, ' unit(s): ', scores)
        tmp.append(scores.mean()) # This list has the mean cross-val scores

Cross Validation Score for  1  layer(s) and  1  unit(s):  [0.99345768 0.99471047 0.9920657  0.99317834 0.99484895]
Cross Validation Score for  1  layer(s) and  2  unit(s):  [0.52463808 0.52463808 0.52477728 0.52471112 0.52471112]
Cross Validation Score for  1  layer(s) and  3  unit(s):  [0.99471047 0.99471047 0.99276169 0.99415286 0.99554504]
Cross Validation Score for  1  layer(s) and  4  unit(s):  [0.52463808 0.52463808 0.52477728 0.52471112 0.52471112]
Cross Validation Score for  1  layer(s) and  5  unit(s):  [0.99373608 0.99484967 0.9924833  0.99415286 0.99582347]
Cross Validation Score for  2  layer(s) and  1  unit(s):  [0.99387528 0.99401448 0.9923441  0.99317834 0.99498817]
Cross Validation Score for  2  layer(s) and  2  unit(s):  [0.99317929 0.99471047 0.9924833  0.99387443 0.99568425]
Cross Validation Score for  2  layer(s) and  3  unit(s):  [0.99457127 0.99429287 0.99262249 0.99359599 0.99582347]
Cross Validation Score for  2  layer(s) and  4  unit(s):  [0.99331849 0.99401448

In [90]:
tmp

[0.9936522279311427,
 0.5246951398175661,
 0.9943761051753288,
 0.5246951398175661,
 0.99420907506495,
 0.9936800714505637,
 0.9939863462884247,
 0.9941812199182245,
 0.9940698884739921,
 0.9937079149699845,
 0.9937357352347955,
 0.9941533880261083,
 0.9943204297637921,
 0.9942090983195598,
 0.9940141936836138,
 0.9942647427249505,
 0.9939585260236138,
 0.9943482771589812,
 0.9935130490917216,
 0.9942368875782247,
 0.993902827357467,
 0.9939585143963088,
 0.993902811854394,
 0.9939306631253514,
 0.9940977281176447]

In [94]:
np.max(tmp) # Get the maximum cross-val score

0.9943761051753288

In [96]:
# Find the index which has the maximum cross-val score
for i in range(25):
    #print(i, ' : ', tmp[i])
    if tmp[i] == 0.9943761051753288:
        print(i+1, ' : ', tmp[i])

3  :  0.9943761051753288


In [33]:
# 1 hidden layers with 3 hidden units is the ideal solution here.

In [189]:
MLP_clf = MLPClassifier(hidden_layer_sizes=(3,1), random_state=2, max_iter=500, alpha=0.01).fit(x_train_tfidf, y_train)

In [190]:
y_pred = MLP_clf.predict(x_test_tfidf) # Prediction on test data using MLP model
y_pred

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [191]:
# Find accuracy score
from sklearn.metrics import accuracy_score
accuracy_score_MLP = accuracy_score(y_test, y_pred)
accuracy_score_MLP

0.9951002227171493

In [192]:
# Compute confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[4615,   20],
       [  24, 4321]], dtype=int64)

### Analysis of algorithms

In [223]:
comparision = {} # Dictionary to maintain the accuracy scores of all the algorithms
comparision['Decision Tree'] = accuracy_score_DT
comparision['Random Forest'] = accuracy_score_RF
comparision['Logistic Regression'] = accuracy_score_LR
comparision['K-Nearest Neighbors'] = accuracy_score_KNN
comparision['Naive Bayes'] = accuracy_score_NB
comparision['Multi-layer Perceptron'] = accuracy_score_MLP

In [224]:
comparision

{'Decision Tree': 0.994543429844098,
 'Random Forest': 0.9806236080178173,
 'Logistic Regression': 0.9876391982182628,
 'K-Nearest Neighbors': 0.6347438752783965,
 'Naive Bayes': 0.9391982182628063,
 'Multi-layer Perceptron': 0.9951002227171493}

In [225]:
# It is clear that MLP works best in this case

In [281]:
from sklearn.neural_network import MLPClassifier

# Fit the data using MLP Classifier
best_clf = MLPClassifier(hidden_layer_sizes=(3,1), random_state=2, max_iter=500, alpha=0.01).fit(x_train_tfidf, y_train)

In [282]:
best_clf.predict(x_test_tfidf) # Predict test data using MLP Classifier

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

### Predicting in real time

In [298]:
pd.set_option('display.max_colwidth', None)
print(df['text'][0]) # Example text to predict if it is fake or not (this example is 'fake news')
#print(df['target'][12299])

0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       

In [299]:
# Input text
corpus = ["Donald Trump wish Americans Happy New Year leave that. Instead, give shout enemies, haters dishonest fake news media. The former reality show star one job it. As Country rapidly grows stronger smarter, I want wish friends, supporters, enemies, haters, even dishonest Fake News Media, Happy Healthy New Year, President Angry Pants tweeted. 2018 great year America! As Country rapidly grows stronger smarter, I want wish friends, supporters, enemies, haters, even dishonest Fake News Media, Happy Healthy New Year. 2018 great year America! Donald J. Trump (@realDonaldTrump) December 31, 2017Trump tweet went welll expect.What kind president sends New Year greeting like despicable, petty, infantile gibberish? Only Trump! His lack decency even allow rise gutter long enough wish American citizens happy new year! Bishop Talbert Swan (@TalbertSwan) December 31, 2017no one likes Calvin (@calvinstowell) December 31, 2017Your impeachment would make 2018 great year America, I also accept regaining control Congress. Miranda Yaver (@mirandayaver) December 31, 2017Do hear talk? When include many people hate wonder? Why hate me? Alan Sandoval (@AlanSandoval13) December 31, 2017Who uses word Haters New Years wish?? Marlene (@marlene399) December 31, 2017You say happy new year? Koren pollitt (@Korencarpenter) December 31, 2017Here Trump New Year Eve tweet 2016.Happy New Year all, including many enemies fought lost badly know do. Love! Donald J. Trump (@realDonaldTrump) December 31, 2016This nothing new Trump. He years.Trump directed messages enemies haters New Year s, Easter, Thanksgiving, anniversary 9/11. pic.twitter.com/4FPAe2KypA Daniel Dale (@ddale8) December 31, 2017Trump holiday tweets clearly presidential.How long work Hallmark becoming President? Steven Goodine (@SGoodine) December 31, 2017He always like . . . difference last years, filter breaking down. Roy Schulze (@thbthttt) December 31, 2017Who, apart teenager uses term haters? Wendy (@WendyWhistles) December 31, 2017he fucking 5 year old Who Knows (@rainyday80) December 31, 2017So, people voted hole thinking would change got power, wrong! 70-year-old men change year older.Photo Andrew Burton/Getty Images."]

# Convert the input text to vectors using TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
x_tfidf = tfidf.fit_transform(corpus)

# Consider only the array, and not sparse matrix
x = x_tfidf.data
print(type(x))
print(x.shape[0]) # input size is small - 191

<class 'numpy.ndarray'>
191


In [300]:
best_clf.n_features_in_ # The input of MLPCLassifier is huge - 111657

111657

In [301]:
inp_len = 111657
#print(x.shape[0])

# Make the input text size compatible with MLPClassifier's input
if x.shape[0] > inp_len:
    x = x[:inp_len]
else:
    x = list(x)
    x = x + [0]*(inp_len - len(x))
    x = np.array(x)
x.shape[0]

111657

In [302]:
x = x.reshape(1, -1) # Make the input a 2-D array, instead of 1-D array (as MLPClassifier takes in only 2-D array)

In [303]:
from sklearn.neural_network import MLPClassifier
prediction = best_clf.predict(x) # Predict using MLP Classifier
prediction # Output class is 0, which is what it is

array([0], dtype=int64)